service: fink
provider:
    name: aws
    runtime: rust
plugins:
    - serverless-build-client
    - serverless-finch
    - serverless-rust
package:
    individually: true
functions:
    echo: 
        handler: backend
        events:
            - websocket:
                route: $connect
            - websocket:
                route: $disconnect
            - websocket:
                route: $default
                routeResponseSelectionExpression: $default
        environment:
            RUST_LOG: DEBUG
custom:
    buildClient:
        packager: yarn
        command: workspace frontend run build
        environment:
            REACT_APP_WS_URL: ${cf:fink-dev.ServiceEndpointWebsocket}
    client:
        bucketName: ozbe-fink-dev
        distributionFolder: frontend/build
       